### ISSUE TITLE
Heroes path does not get converted

### ISSUE THREAD

**Issue by senolfeldmann** [JordanZeotni/BotW-Save-Manager#1]
Title says it all. The original from Weml0 also had problems with this. It seems your program does not touch heroes path at all.

**Comment by DeltaJordan** [comment]
1. Please make sure you post your log when creating an issue. The latest release has added extensive logging which would answer most if not all of my next questions.
2. I'm not sure exactly what you mean by heroes path. Do you mean the DLC map feature that shows where Link has gone in the past? If so, it is interesting this is the first time anyone has brought up this issue.
3. If possible upload your save as well so I can see the file structure compared to my test cases. If you used the latest release and have a log, it will show the directory tree of the save to me and uploading your save is not necessary, but will still be helpful.

**Comment by xombiemp** [comment]
@DeltaJordan 
I can confirm that this is an issue. Yes, it is the DLC map feature that shows everywhere you've gone.

There is also a solution that I've tested and can confirm does work.
See this issue comment https://github.com/WemI0/BOTW_SaveConv/issues/1#issuecomment-405082797

After I ran the conversion tool, I used a hex editor on all the trackblockXX.sav files and I copied bytes 0x0 to 0x7 from the original Wii U save and pasted it over the converted Switch save in the same place.  Then I swapped values 0x4 and 0x5.  After doing this with all the files and restoring that save, I can now see my full hero's path on the map.

**Comment by DeltaJordan** [comment]
Alright this seems like its going to need some extra work for those save files. I'll look into it when I have some time to, or if you know how to implement that feel free to do so and pull request it.

**Comment by Stefferp** [comment]
> I copied bytes 0x0 to 0x7 from the original Wii U save and pasted it over the converted Switch save in the same place. Then I swapped values 0x4 and 0x5. After doing this with all the files and restoring that save, I can now see my full hero's path on the map.

Did you try this on save data with multiple trackblock files? I just ran the conversion tool on my old wii u save and it seems that only trackblock00.sav works properly, all the other ones don't load (I have 15 of them)

**Comment by senolfeldmann** [comment]
> > I copied bytes 0x0 to 0x7 from the original Wii U save and pasted it over the converted Switch save in the same place. Then I swapped values 0x4 and 0x5. After doing this with all the files and restoring that save, I can now see my full hero's path on the map.
> 
> Did you try this on save data with multiple trackblock files? I just ran the conversion tool on my old wii u save and it seems that only trackblock00.sav works properly, all the other ones don't load (I have 15 of them)

Sorry for the very late answer, but in case anyone else stumbles upon this thread: Yes, I tried this on save data with multiple trackblock files and it worked.
