### ISSUE TITLE
Bug when converting to WII U, cemu loads the save but I land at the very start of the game

### ISSUE THREAD

**Issue by fteppe** [JordanZeotni/BotW-Save-Manager#13]
Hello, I don't know if you are still monitoring this, but I wanted to go from Yuzu to Cemu, and while the program says the transformation was successfull, Cemu can't load the save.

Zelda is 1.6 on switch with all DLC and 1.5 on wii U with all DLC (version 208 DLC 80). The game sees that there are multiple saves, but it doesn't load the image, the date, and when I load it, there are no errors but I land at the resurrection shrine as if I had just launched the game for the first time (except it doesn't play the opening cinematic)

I attached both save files.

Hopefully you can help me!
[save Switch.zip](https://github.com/DeltaJordan/BotW-Save-Manager/files/6909261/save.Switch.zip)
[save Wiiu.zip](https://github.com/DeltaJordan/BotW-Save-Manager/files/6909262/save.Wiiu.zip)

here's the log 
[30-07-21-4.log](https://github.com/DeltaJordan/BotW-Save-Manager/files/6909320/30-07-21-4.log)

**Comment by fteppe** [comment]
Nevermind I didn't understand how the save to file worked. Sorry.

**Comment by eisaimalaks123** [comment]
Hi, can i know how did you do that? im literally trying to convers save files from yuzu to cemu about 5 hours and i cant find the way

**Comment by fteppe** [comment]
I think all I had to do once the translation was done was to save the files somewhere, that's what the bottom button is for, it has been a while but I think that was the solution.
