### ISSUE TITLE
Only converted the saves; cannot run game in Cemu

### ISSUE THREAD

**Issue by Pnoob28** [JordanZeotni/BotW-Save-Manager#19]
There is no BotwSaveEditor.exe as mentioned in Setup. The link also doesn't work. I want to add, it might be the post with the file may be removed or deleted. If that is the case, then is there any other way to download the file? This issue was not noticed by anyone before as far as I searched, which is why I'm posting this here.

**Comment by Pnoob28** [comment]
I want to add, it might be the post with the file may be removed or deleted. If that is the case, then is there any other way to download the file?

**Comment by Pnoob28** [comment]
EDIT: Sorry, found the actual file for the app was different. I found it now. I now have a different issue. I converted my switch save to a wii u save successfully, but I cannot run the game in cemu, as there is no .rpx and it has only converted the saves. Please tell me what I can do to play it.

P.S. I tried to replace the save files from save directory with the newly converted save files, but that just restarted the game from the beginning.

**Comment by DeltaJordan** [comment]
I'm not sure what you're looking for in this app, but it **only** converts saves.
