### ISSUE TITLE
I can't convert saves in master mode

### ISSUE THREAD

**Issue by Tsuhirito** [JordanZeotni/BotW-Save-Manager#4]
I tried to convert my save from switch to wiiu but I get this error only for save number 2 and 3 because they are in master mode.  If I click yes I can see only number 0 and 1 for normal difficulty.

![zelda](https://user-images.githubusercontent.com/29732138/71322324-b78fca80-24c6-11ea-96ce-2fbec3105523.jpg)

![zelda1](https://user-images.githubusercontent.com/29732138/71322328-ba8abb00-24c6-11ea-8ebc-a80aea7a6785.jpg)

![zelda2](https://user-images.githubusercontent.com/29732138/71322370-22d99c80-24c7-11ea-8bb7-36fc334722a0.JPG)

**Comment by DeltaJordan** [comment]
Try the latest version, and if the issue persists feel free to reopen the issue. For now, closing.
