### ISSUE TITLE
error CS0103: The name 'From' does not exist in the current context [C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master\BOTW_SaveConv.csproj]

### ISSUE THREAD

**Issue by charlie-horse** [JordanZeotni/BotW-Save-Manager#7]
I may be overlooking something as I am very new to this however I looked at the file in VSC and I didn't see any identifier such as From or To.

`C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master> dotnet run
Program.cs(63,65): error CS0103: The name 'From' does not exist in the current context [C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master\BOTW_SaveConv.csproj]
Program.cs(63,131): error CS0103: The name 'To' does not exist in the current context [C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master\BOTW_SaveConv.csproj]
Program.cs(122,73): error CS0103: The name 'From' does not exist in the current context [C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master\BOTW_SaveConv.csproj]
Program.cs(122,87): error CS0103: The name 'To' does not exist in the current context [C:\Users\charl\Downloads\BotW-Save-Manager-master\BotW-Save-Manager-master\BOTW_SaveConv.csproj]
dotnet : 
At line:1 char:1
+ dotnet run
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The build failed. Fix the build errors and run again.`

**Comment by DeltaJordan** [comment]
Apologies, an old project was included in the source. I have removed it in the above commit.
